.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. lekcoin_qt test_lekcoin_qt
clean: FORCE
	$(MAKE) -C .. lekcoin_qt_clean test_lekcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_lekcoin_qt_check
lekcoin-qt lekcoin-qt.exe: FORCE
	 $(MAKE) -C .. lekcoin_qt
